package com.avies.backend.question;

import com.avies.backend.dto.request.*;
import com.avies.backend.dto.response.QuestionResponse;
import com.avies.backend.entity.*;
import com.avies.backend.entity.enums.*;
import com.avies.backend.exception.*;
import com.avies.backend.repository.*;
import com.avies.backend.service.QuestionService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.validation.ConstraintViolationException;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.annotation.Transactional;
import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

/** Kiểm tra nghiệp vụ cùng repository, transaction và database H2 thật trong bộ nhớ. */
@SpringJUnitConfig(QuestionPersistenceTestConfig.class)
@Transactional
class QuestionServiceIntegrationTest {
    /** Dịch vụ thật được kiểm tra qua proxy validation và transaction. */
    @Autowired private QuestionService service;
    /** Kho câu hỏi thật để xác minh kết quả lưu. */
    @Autowired private QuestionRepository questions;
    /** Kho phân công dùng tạo dữ liệu test. */
    @Autowired private LecturerSubjectAssignmentRepository assignments;
    /** Kho nhật ký để kiểm tra thao tác lặp lại. */
    @Autowired private QuestionAuditLogRepository audits;
    /** Entity manager của cơ sở dữ liệu tạm. */
    @PersistenceContext private EntityManager entityManager;
    /** Nguồn dữ liệu trong bộ nhớ, không phải nguồn của ứng dụng. */
    @Autowired private DataSource dataSource;
    /** Chủ sở hữu câu hỏi được phân công môn thứ nhất. */
    private User owner;
    /** Giảng viên cùng môn nhưng khác chủ sở hữu. */
    private User colleague;
    /** Giảng viên không được phân công môn thứ nhất. */
    private User outsider;
    /** Quản trị viên để kiểm tra quyền và giới hạn nghiệp vụ. */
    private User admin;
    /** Sinh viên không được truy cập ngân hàng. */
    private User student;
    /** Môn học chính của bộ dữ liệu test. */
    private Subject subject;
    /** Môn học không được phân công cho chủ sở hữu. */
    private Subject otherSubject;

    /** Khởi tạo bộ dữ liệu riêng cho mỗi test; transaction được rollback sau khi hoàn tất. */
    @BeforeEach
    void setUp() {
        new JdbcTemplate(dataSource).execute("""
                CREATE TABLE IF NOT EXISTS aives.student_exam_questions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    question_id BIGINT NOT NULL REFERENCES aives.questions(id))
                """);
        Role lecturer = role("LECTURER");
        owner = user("owner", lecturer);
        colleague = user("colleague", lecturer);
        outsider = user("outsider", lecturer);
        admin = user("admin", role("ADMIN"));
        student = user("student", role("STUDENT"));
        subject = subject("SWD392");
        otherSubject = subject("PRJ301");
        assignments.save(LecturerSubjectAssignment.builder().lecturer(owner).subject(subject).build());
        assignments.save(LecturerSubjectAssignment.builder().lecturer(colleague).subject(subject).build());
        entityManager.flush();
        login(owner);
    }

    /** Không để thông tin đăng nhập của test trước ảnh hưởng test sau. */
    @AfterEach
    void clearSecurity() { SecurityContextHolder.clearContext(); }

    /** Tạo câu hỏi phải chuẩn hóa tiếng Việt, loại trùng chủ đề và gán giá trị do server quản lý. */
    @Test
    void createsManualDraftWithNormalizedTopicsAndAudit() {
        QuestionCreationRequest request = creation("  Giải thích HashTable.  ");
        request.setTopics(List.of(" Array ", "array", "HashTable"));
        QuestionResponse response = service.createQuestion(request);
        assertThat(response.getContent()).isEqualTo("Giải thích HashTable.");
        assertThat(response.getTopics()).containsExactlyInAnyOrder("Array", "HashTable");
        assertThat(response.getSourceType()).isEqualTo(QuestionSourceType.MANUAL);
        assertThat(response.getStatus()).isEqualTo(QuestionStatus.DRAFT);
        assertThat(response.getCreatedById()).isEqualTo(owner.getId());
        assertThat(response.getVersion()).isZero();
        assertThat(response.getCreatedAt()).isNotNull();
        assertThat(audits.count()).isEqualTo(1);
        entityManager.clear();
        assertThat(service.getQuestion(response.getId()).getTopics()).hasSize(2);
    }

    /** Giảng viên không được tạo câu hỏi ngoài môn được phân công. */
    @Test
    void rejectsCreationOutsideAssignment() {
        QuestionCreationRequest request = creation("Nội dung");
        request.setSubjectId(otherSubject.getId());
        expectError(() -> service.createQuestion(request), ErrorCode.SUBJECT_NOT_ASSIGNED);
        assertThat(questions.count()).isZero();
    }

    /** Admin tạo được câu hỏi ở môn chưa có phân công nhưng môn vẫn phải tồn tại. */
    @Test
    void adminCanCreateAcrossSubjectsButMissingSubjectFails() {
        login(admin);
        QuestionCreationRequest request = creation("Nội dung");
        request.setSubjectId(otherSubject.getId());
        assertThat(service.createQuestion(request).getSubjectId()).isEqualTo(otherSubject.getId());
        request.setSubjectId(Long.MAX_VALUE);
        expectError(() -> service.createQuestion(request), ErrorCode.SUBJECT_NOT_EXISTED);
    }

    /** Cùng môn chỉ được xem câu đã duyệt của người khác, không thấy bản nháp riêng. */
    @Test
    void hidesOtherDraftsAndAllowsPublishedQuestionsWithinSubject() {
        QuestionResponse draft = service.createQuestion(creation("Bản nháp"));
        QuestionResponse published = service.createQuestion(creation("Đã duyệt"));
        publish(published.getId());
        login(colleague);
        expectError(() -> service.getQuestion(draft.getId()), ErrorCode.QUESTION_NOT_FOUND);
        assertThat(service.getQuestion(published.getId()).getId()).isEqualTo(published.getId());
        assertThat(service.searchQuestions(new QuestionSearchRequest()).getTotalElements()).isEqualTo(1);
        login(outsider);
        expectError(() -> service.getQuestion(published.getId()), ErrorCode.QUESTION_NOT_FOUND);
        assertThat(service.searchQuestions(new QuestionSearchRequest()).getTotalElements()).isZero();
    }

    /** Bộ lọc tác giả không được vượt quyền và tổng số trang không được làm lộ bản nháp khác. */
    @Test
    void paginationAndFiltersRespectAccessScope() {
        service.createQuestion(creation("Câu thứ nhất"));
        Long approvedId = service.createQuestion(creation("Câu thứ hai")).getId();
        publish(approvedId);
        login(colleague);
        QuestionSearchRequest filter = new QuestionSearchRequest();
        filter.setCreatedById(owner.getId());
        filter.setSize(1);
        assertThat(service.searchQuestions(filter).getTotalElements()).isEqualTo(1);
        filter.setPage(1);
        assertThat(service.searchQuestions(filter).getItems()).isEmpty();
    }

    /** Tìm chủ đề không phân biệt hoa thường, từ khóa phần trăm được hiểu là ký tự thường. */
    @Test
    void filtersTopicsAndEscapesLikeWildcards() {
        QuestionCreationRequest request = creation("Độ chính xác 100% trong Array");
        request.setTopics(List.of("Array", "HashTable"));
        service.createQuestion(request);
        service.createQuestion(creation("Một câu khác"));
        QuestionSearchRequest filter = new QuestionSearchRequest();
        filter.setTopic(" array ");
        assertThat(service.searchQuestions(filter).getTotalElements()).isEqualTo(1);
        filter.setTopic(null);
        filter.setKeyword("%");
        assertThat(service.searchQuestions(filter).getTotalElements()).isEqualTo(1);
    }

    /** PATCH hỗ trợ xóa giá trị tùy chọn và giữ các trường không được gửi. */
    @Test
    void patchClearsNullableFieldsAndPreservesOmittedContent() {
        QuestionCreationRequest request = creation("Giữ nội dung");
        request.setReferenceAnswer("Đáp án");
        request.setBloomLevel(BloomLevel.APPLY);
        request.setAnswerTimeLimitSeconds(120);
        request.setTopics(List.of("Array"));
        QuestionResponse created = service.createQuestion(request);
        QuestionUpdateRequest patch = patch(created);
        patch.setReferenceAnswer(null);
        patch.setBloomLevel(null);
        patch.setAnswerTimeLimitSeconds(null);
        patch.setTopics(List.of());
        QuestionResponse result = service.updateQuestion(created.getId(), patch);
        assertThat(result.getContent()).isEqualTo("Giữ nội dung");
        assertThat(result.getReferenceAnswer()).isNull();
        assertThat(result.getBloomLevel()).isNull();
        assertThat(result.getAnswerTimeLimitSeconds()).isNull();
        assertThat(result.getTopics()).isEmpty();
        assertThat(result.getVersion()).isGreaterThan(created.getVersion());
        entityManager.clear();
        assertThat(service.getQuestion(created.getId()).getTopics()).isEmpty();
    }

    /** Gửi lại giá trị không đổi không tạo lần cập nhật giả hoặc nhật ký thừa. */
    @Test
    void unchangedPatchDoesNotIncrementVersionOrAudit() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        QuestionUpdateRequest patch = patch(created);
        patch.setContent("  Nội dung  ");
        assertThat(service.updateQuestion(created.getId(), patch).getVersion()).isEqualTo(created.getVersion());
        assertThat(service.updateQuestion(created.getId(), patch).getVersion()).isEqualTo(created.getVersion());
        assertThat(audits.count()).isEqualTo(1);
    }

    /** Thay thế collection trên entity vừa nạp phải được lưu thật và không ảnh hưởng câu khác. */
    @Test
    void replacesTopicsAfterReloadWithoutChangingOtherQuestions() {
        QuestionCreationRequest request = creation("Câu thứ nhất");
        request.setTopics(List.of("Array", "HashTable"));
        QuestionResponse first = service.createQuestion(request);
        request.setContent("Câu thứ hai");
        QuestionResponse second = service.createQuestion(request);
        entityManager.clear();
        QuestionUpdateRequest patch = patch(first);
        patch.setTopics(List.of("Tree", "tree"));
        service.updateQuestion(first.getId(), patch);
        entityManager.clear();
        assertThat(service.getQuestion(first.getId()).getTopics()).containsExactly("Tree");
        assertThat(service.getQuestion(second.getId()).getTopics()).containsExactlyInAnyOrder("Array", "HashTable");
    }

    /** Xóa câu hỏi kéo theo rubric/tiêu chí riêng nhưng giữ nhật ký thao tác. */
    @Test
    void deletesOwnedRubricAndCriteriaWithDraft() {
        QuestionResponse created = service.createQuestion(creation("Câu có rubric"));
        Question question = questions.findById(created.getId()).orElseThrow();
        Rubric rubric = Rubric.builder().question(question).title("Rubric riêng").build();
        RubricCriterion criterion = RubricCriterion.builder().rubric(rubric).criterionText("Giải thích đúng")
                .pointWeight(java.math.BigDecimal.TEN).build();
        rubric.getCriteria().add(criterion);
        question.setRubric(rubric);
        entityManager.persist(rubric);
        entityManager.flush();
        Long rubricId = rubric.getId();
        service.deleteQuestion(created.getId());
        entityManager.clear();
        assertThat(entityManager.find(Rubric.class, rubricId)).isNull();
        assertThat(audits.count()).isEqualTo(2);
    }

    /** Client dùng version cũ không được ghi đè nội dung vừa được cập nhật. */
    @Test
    void rejectsStaleVersion() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        QuestionUpdateRequest patch = patch(created);
        patch.setContent("Lần sửa đầu");
        service.updateQuestion(created.getId(), patch);
        patch.setContent("Lần sửa từ dữ liệu cũ");
        expectError(() -> service.updateQuestion(created.getId(), patch), ErrorCode.QUESTION_VERSION_CONFLICT);
    }

    /** Câu đã duyệt không được sửa trực tiếp kể cả bởi quản trị viên. */
    @Test
    void adminCannotBypassDraftRule() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        publish(created.getId());
        login(admin);
        QuestionUpdateRequest patch = patch(created);
        patch.setContent("Nội dung mới");
        expectError(() -> service.updateQuestion(created.getId(), patch), ErrorCode.QUESTION_NOT_EDITABLE);
        expectError(() -> service.deleteQuestion(created.getId()), ErrorCode.QUESTION_NOT_EDITABLE);
    }

    /** Quyền xem câu đã duyệt của đồng nghiệp không đồng nghĩa quyền sửa hoặc xóa. */
    @Test
    void colleagueCannotEditOrDeletePublishedQuestion() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        publish(created.getId());
        login(colleague);
        QuestionUpdateRequest patch = patch(created);
        patch.setContent("Nội dung mới");
        expectError(() -> service.updateQuestion(created.getId(), patch), ErrorCode.UNAUTHORIZED);
        expectError(() -> service.deleteQuestion(created.getId()), ErrorCode.UNAUTHORIZED);
    }

    /** Xóa lặp lại giữ cùng kết quả, không ghi nhật ký xóa nhiều lần. */
    @Test
    void deleteIsIdempotentAndPreservesAudit() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        service.deleteQuestion(created.getId());
        service.deleteQuestion(created.getId());
        assertThat(questions.existsById(created.getId())).isFalse();
        assertThat(audits.count()).isEqualTo(2);
        assertThat(audits.findAll()).extracting(QuestionAuditLog::getAction).containsExactlyInAnyOrder("CREATED", "DELETED");
    }

    /** Chặn sửa và xóa câu đã được tham chiếu dù trạng thái dữ liệu đang là bản nháp. */
    @Test
    void blocksChangesToExamReferencedQuestion() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        new JdbcTemplate(dataSource).update("insert into aives.student_exam_questions(question_id) values (?)", created.getId());
        QuestionUpdateRequest patch = patch(created);
        patch.setContent("Nội dung mới");
        expectError(() -> service.updateQuestion(created.getId(), patch), ErrorCode.QUESTION_IN_USE);
        expectError(() -> service.deleteQuestion(created.getId()), ErrorCode.QUESTION_IN_USE);
    }

    /** Bản lưu trữ không được chỉnh sửa hoặc xuất hiện trong danh sách hoạt động. */
    @Test
    void archivedQuestionsAreExcludedAndNotEditable() {
        QuestionResponse created = service.createQuestion(creation("Nội dung"));
        questions.findById(created.getId()).orElseThrow().setArchivedAt(OffsetDateTime.now());
        entityManager.flush();
        assertThat(service.searchQuestions(new QuestionSearchRequest()).getTotalElements()).isZero();
        QuestionSearchRequest filter = new QuestionSearchRequest();
        filter.setArchived(true);
        assertThat(service.searchQuestions(filter).getTotalElements()).isEqualTo(1);
        expectError(() -> service.deleteQuestion(created.getId()), ErrorCode.QUESTION_NOT_EDITABLE);
    }

    /** Role hiện tại trong database được kiểm tra lại ngay cả khi gọi thẳng service. */
    @Test
    void rejectsStudentAndUnauthenticatedCaller() {
        login(student);
        expectError(() -> service.searchQuestions(new QuestionSearchRequest()), ErrorCode.UNAUTHORIZED);
        SecurityContextHolder.clearContext();
        expectError(() -> service.getQuestion(1L), ErrorCode.UNAUTHENTICATED);
    }

    /** Validation service chặn thời gian âm, PATCH rỗng và ký tự null không được PostgreSQL hỗ trợ. */
    @Test
    void validatesBoundaryCases() {
        QuestionCreationRequest request = creation("Nội dung");
        request.setAnswerTimeLimitSeconds(0);
        assertThatThrownBy(() -> service.createQuestion(request)).isInstanceOf(ConstraintViolationException.class);
        request.setAnswerTimeLimitSeconds(null);
        request.setContent("Nội\0dung");
        expectError(() -> service.createQuestion(request), ErrorCode.INVALID_REQUEST);
        QuestionUpdateRequest empty = new QuestionUpdateRequest();
        empty.setExpectedVersion(0L);
        assertThatThrownBy(() -> service.updateQuestion(1L, empty)).isInstanceOf(ConstraintViolationException.class);
    }

    /** Tạo vai trò với đầy đủ thuộc tính bắt buộc. */
    private Role role(String code) {
        Role value = Role.builder().code(code).name(code).build();
        entityManager.persist(value);
        return value;
    }

    /** Tạo tài khoản độc lập, không cần mật khẩu hoặc JWT thật. */
    private User user(String name, Role role) {
        User value = User.builder().username(name).email(name + "@test.invalid").fullName(name).role(role).build();
        entityManager.persist(value);
        return value;
    }

    /** Tạo môn học phục vụ kiểm tra phân công. */
    private Subject subject(String code) {
        Subject value = Subject.builder().code(code).name(code).build();
        entityManager.persist(value);
        return value;
    }

    /** Giả lập người dùng đã được tầng bảo mật xác thực. */
    private void login(User user) {
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(user.getUsername(), "unused", List.of()));
    }

    /** Tạo request mặc định hợp lệ để từng test chỉ thay đổi dữ liệu cần kiểm tra. */
    private QuestionCreationRequest creation(String content) {
        QuestionCreationRequest request = new QuestionCreationRequest();
        request.setSubjectId(subject.getId());
        request.setContent(content);
        return request;
    }

    /** Tạo request PATCH mang đúng version vừa đọc. */
    private QuestionUpdateRequest patch(QuestionResponse question) {
        QuestionUpdateRequest request = new QuestionUpdateRequest();
        request.setExpectedVersion(question.getVersion());
        return request;
    }

    /** Chuẩn bị câu đã duyệt để kiểm tra quyền đọc; không bổ sung API duyệt ngoài phạm vi. */
    private void publish(Long id) {
        Question question = questions.findById(id).orElseThrow();
        question.setStatus(QuestionStatus.APPROVED);
        question.setIsApproved(true);
        entityManager.flush();
    }

    /** Kiểm tra chính xác mã lỗi nghiệp vụ thay vì chỉ kiểm tra có exception. */
    private void expectError(Runnable operation, ErrorCode code) {
        assertThatThrownBy(operation::run).isInstanceOfSatisfying(AppException.class,
                exception -> assertThat(exception.getErrorCode()).isEqualTo(code));
    }
}
