package com.avies.backend.question;

import com.avies.backend.dto.request.*;
import com.avies.backend.dto.response.QuestionResponse;
import com.avies.backend.entity.*;
import com.avies.backend.exception.*;
import com.avies.backend.repository.*;
import com.avies.backend.service.QuestionService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import javax.sql.DataSource;
import java.util.List;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doThrow;

/** Kiểm tra commit/rollback và hai request cạnh tranh bằng các transaction thật, tách biệt. */
@SpringJUnitConfig(QuestionPersistenceTestConfig.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
class QuestionTransactionTest {
    /** Dịch vụ thật mở transaction riêng cho mỗi lần gọi. */
    @Autowired private QuestionService service;
    /** Kho câu hỏi để xác minh kết quả sau commit hoặc rollback. */
    @Autowired private QuestionRepository questions;
    /** Spy chỉ gây lỗi ghi nhật ký trong bài kiểm tra rollback. */
    @MockitoSpyBean private QuestionAuditLogRepository audits;
    /** Transaction manager của H2 cô lập. */
    @Autowired private PlatformTransactionManager transactionManager;
    /** Entity manager gắn với transaction của mỗi luồng. */
    @PersistenceContext private EntityManager entityManager;
    /** Database tạm, dùng tạo bảng tham chiếu bài thi tối thiểu. */
    @Autowired private DataSource dataSource;
    /** Môn học được tạo và commit trước khi chạy các request cạnh tranh. */
    private Long subjectId;

    /** Tạo fixture đã commit để nhiều luồng đều nhìn thấy cùng dữ liệu. */
    @BeforeEach
    void setUp() {
        new JdbcTemplate(dataSource).execute("""
                CREATE TABLE aives.student_exam_questions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    question_id BIGINT NOT NULL REFERENCES aives.questions(id))
                """);
        new TransactionTemplate(transactionManager).executeWithoutResult(status -> {
            Role role = Role.builder().code("ADMIN").name("Quản trị").build();
            entityManager.persist(role);
            entityManager.persist(User.builder().username("admin").email("admin@test.invalid")
                    .fullName("Quản trị test").role(role).build());
            Subject subject = Subject.builder().code("SWD392").name("Thiết kế phần mềm").build();
            entityManager.persist(subject);
            subjectId = subject.getId();
        });
        login();
    }

    /** Xóa context bảo mật trên luồng chạy test sau mỗi bài kiểm tra. */
    @AfterEach
    void clearSecurity() { SecurityContextHolder.clearContext(); }

    /** Ghi nhật ký thất bại phải rollback cả câu hỏi lẫn nhãn đã flush xuống database. */
    @Test
    void rollsBackQuestionAndTopicsWhenAuditFails() {
        doThrow(new IllegalStateException("Lỗi nhật ký giả lập")).when(audits).save(any(QuestionAuditLog.class));
        assertThatThrownBy(() -> service.createQuestion(creation())).isInstanceOf(IllegalStateException.class);
        assertThat(questions.count()).isZero();
        assertThat(new JdbcTemplate(dataSource).queryForObject("select count(*) from aives.question_topics", Long.class)).isZero();
        assertThat(audits.count()).isZero();
    }

    /** Hai request cùng version chỉ có một request thành công, request còn lại nhận xung đột. */
    @Test
    void concurrentUpdatesDoNotOverwriteEachOther() throws Exception {
        QuestionResponse created = service.createQuestion(creation());
        CyclicBarrier start = new CyclicBarrier(2);
        try (ExecutorService executor = Executors.newFixedThreadPool(2)) {
            Future<String> first = executor.submit(() -> updateConcurrently(created, "Nội dung A", start));
            Future<String> second = executor.submit(() -> updateConcurrently(created, "Nội dung B", start));
            assertThat(List.of(first.get(15, TimeUnit.SECONDS), second.get(15, TimeUnit.SECONDS)))
                    .containsExactlyInAnyOrder("UPDATED", "QUESTION_VERSION_CONFLICT");
        }
        assertThat(service.getQuestion(created.getId()).getVersion()).isEqualTo(created.getVersion() + 1);
        assertThat(audits.count()).isEqualTo(2);
    }

    /** Hai yêu cầu xóa đồng thời cùng thành công và chỉ có một sự kiện xóa. */
    @Test
    void concurrentDeletesRemainIdempotent() throws Exception {
        Long id = service.createQuestion(creation()).getId();
        CyclicBarrier start = new CyclicBarrier(2);
        try (ExecutorService executor = Executors.newFixedThreadPool(2)) {
            Callable<Boolean> delete = () -> {
                login();
                try {
                    start.await(5, TimeUnit.SECONDS);
                    service.deleteQuestion(id);
                    return true;
                } finally {
                    SecurityContextHolder.clearContext();
                }
            };
            Future<Boolean> first = executor.submit(delete);
            Future<Boolean> second = executor.submit(delete);
            assertThat(first.get(15, TimeUnit.SECONDS)).isTrue();
            assertThat(second.get(15, TimeUnit.SECONDS)).isTrue();
        }
        assertThat(questions.existsById(id)).isFalse();
        assertThat(audits.count()).isEqualTo(2);
    }

    /** Thực hiện cập nhật sau hàng rào đồng bộ với context đăng nhập riêng theo luồng. */
    private String updateConcurrently(QuestionResponse question, String content, CyclicBarrier start) throws Exception {
        login();
        try {
            QuestionUpdateRequest request = new QuestionUpdateRequest();
            request.setExpectedVersion(question.getVersion());
            request.setContent(content);
            start.await(5, TimeUnit.SECONDS);
            service.updateQuestion(question.getId(), request);
            return "UPDATED";
        } catch (AppException exception) {
            return exception.getErrorCode().name();
        } finally {
            SecurityContextHolder.clearContext();
        }
    }

    /** Tạo request có chủ đề để kiểm tra rollback cả collection. */
    private QuestionCreationRequest creation() {
        QuestionCreationRequest request = new QuestionCreationRequest();
        request.setSubjectId(subjectId);
        request.setContent("Câu hỏi ban đầu");
        request.setTopics(List.of("Array"));
        return request;
    }

    /** Giả lập admin đã đăng nhập trên luồng hiện tại. */
    private void login() {
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken("admin", "unused", List.of()));
    }
}
